### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by JT501**
Bug fix for:
https://github.com/specialtactics/laravel5-api-boilerplate/issues/26

### CODE REVIEW

**Comment by specialtactics** [comment]
Thanks for the PR

I think a better solution is just to put the unset above the array merge there.

I will also add a unit test for this.

**Comment by JT501** [comment]
Great ! It's more simple haha 
Thanks for your projects.
Looking forwards to your new release !

**Comment by specialtactics** [comment]
@hallelujahbaby  No worries, did you want to update your PR? I'm happy to implement it myself, just don't want to diminish your contribution :smile:

**Comment by JT501** [comment]
Cool. I just updated my PR.

**Comment by specialtactics** [comment]
Fantastic, thanks @hallelujahbaby ! I'll tag it momentarily

**Pull request merged**
